/* Create the atxhousing table and import the data from a CSV */
create table atxhousing(
    zpid integer primary key,
    city varchar(300),
    streetAddress varchar(300),
    zipcode integer,
    latitude numeric ,
    longitude numeric,
    propertyTaxRate numeric,
    garageSpaces int ,
    hasAssociation boolean,
    hasCooling boolean ,
    hasGarage boolean,
    hasHeating boolean,
    hasSpa boolean ,
    hasView boolean,
    homeType varchar(30),
    parkingSpaces integer,
    yearBuilt integer,
    latestPrice numeric,
    numPriceChanges integer,
    latest_saledate date,
    latest_salemonth integer,
    latest_saleyear integer,
    latestPriceSource varchar(300),
    numOfPhotos integer,
    numOfAccessibilityFeatures integer,
    numOfAppliances integer,
    numOfParkingFeatures integer,
    numOfPatioAndPorchFeatures integer,
    numOfSecurityFeatures integer,
    numOfWaterfrontFeatures integer,
    numOfWindowFeatures integer,
    numOfCommunityFeatures integer,
    lotSizeSqFt numeric,
    livingAreaSqFt numeric,
    numOfPrimarySchools integer,
    numOfElementarySchools integer,
    numOfMiddleSchools integer,
    numOfHighSchools integer,
    avgSchoolDistance numeric,
    avgSchoolRating numeric,
    avgSchoolSize numeric,
    MedianStudentsPerTeacher numeric,
    numOfBathrooms numeric,
    numOfBedrooms numeric,
    numOfStories numeric )

